#
# Copyright (c) 2015 by Delphix. All rights reserved.
#
---
driver:
  name: vagrant

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true
  requirements_path: requirements-test.txt
  #
  # When testing with Test Kitchen, run the Docker client with
  # "--insecure-registry registry.yourdomain.local" so that we can test pushing
  # to our test private registry.
  #
  extra_vars:
    docker_opts: "--insecure-registry registry.yourdomain.local"

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'
